import React from 'react';

export default function TermsOfService() {
  return (
    <div className="container mx-auto max-w-4xl py-12 px-4">
      <h1 className="text-4xl font-bold mb-8">Terms of Service for Influbot</h1>
      <p className="text-muted-foreground mb-8">Effective Date: {new Date().toLocaleDateString()}</p>

      <div className="space-y-8">
        <section>
          <h2 className="text-2xl font-semibold mb-4">1. Overview</h2>
          <p className="text-muted-foreground">
            Influbot is an AI-powered platform designed to help users improve their on-camera presence through daily video challenges and feedback. By using our website and services, you agree to comply with these terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">2. Accounts</h2>
          <p className="text-muted-foreground">
            To use Influbot, you must create an account and provide accurate information, including your email address. You are responsible for maintaining the confidentiality of your account and password.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">3. Content and AI Processing</h2>
          <p className="text-muted-foreground mb-4">
            By uploading videos to Influbot, you grant us permission to process these videos using third-party AI services (specifically Google AI) for the purpose of providing you with feedback and analysis.
          </p>
          <p className="text-muted-foreground">
            You retain all ownership rights to your content. We do not claim ownership over the videos you upload.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">4. Acceptable Use</h2>
          <p className="text-muted-foreground">
            You agree not to misuse the Service. You must not upload content that is illegal, offensive, or violates the rights of others. We reserve the right to remove any content or suspend accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">5. Disclaimer</h2>
          <p className="text-muted-foreground">
            The feedback provided by our AI system is for educational and self-improvement purposes only. It is generated by artificial intelligence and may not always be perfectly accurate or applicable to every context.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">6. Changes to Terms</h2>
          <p className="text-muted-foreground">
            We reserve the right to modify these terms at any time. We will notify users of any significant changes. Continued use of the Service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">7. Contact</h2>
          <p className="text-muted-foreground">
            Questions about the Terms of Service should be sent to us.
          </p>
        </section>
      </div>
    </div>
  );
}

